name: Print Secret Value

on: [push]

jobs:
  print-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up secrets
      run: |
        echo "YOUR_SECRET_NAME=${{ secrets.YOUR_ORGANIZATION_SECRET_NAME }}" >> $GITHUB_ENV

    - name: Print Secret
      run: echo $YOUR_SECRET_NAME
